name: Run tests
on:
  push:


jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22' ]

    steps:
      - uses: actions/checkout@v4
      - name: Start mockserver
        run: docker run -d -v ./tests/mockserver/config:/config -p 1080:1080 -e MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json --name mockserver-go mockserver/mockserver
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Install dependencies for container
        run: cd docker && go get . && cd -
      - name: Run tests for container
        run: cd docker && go test && cd -
        env:
          NETBOX_URL: http://localhost:1080 
          NETBOX_TOKEN: testing

