name: Run tests
on:
  pull_request:
    branches:
      - "main"    

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    environment: test_ci
    strategy:
      matrix:
        go-version: [ '1.22' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Install dependencies for container
        run: cd docker && go get . && cd -
      - name: Run tests for container
        run: cd docker && go test && cd -
        env:
          NETBOX_URL: ${{ secrets.NETBOX_URL }}
          NETBOX_TOKEN: ${{ secrets.NETBOX_TOKEN }}

